ged/urls.py
from django.conf.urls import url

from .views import FichierList, FichierDetail, FichierCreate, FichierUpdate, FichierDelete

urlpatterns = [
    url(r'^g_$', FichierList.as_view(), name='fichier-list'),
    url(r'^g_(?P<pk>\d+)/$', FichierDetail.as_view(), name='fichier-detail'),
    url(r'^g_create/$', FichierCreate.as_view(), name='fichier-create'),
    url(r'^g_maj/(?P<pk>\d+)/$', FichierUpdate.as_view(), name='fichier-update'),
    url(r'^g_delete/(?P<pk>\d+)/$', FichierDelete.as_view(), name='fichier-delete'),
]

ged/models.py
from django.db import models
from django.db.models import signals
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from wand.image import Image

class Emetteur(models.Model):
    
    nom = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nom

class Destinataire(models.Model):
    
    nom = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nom

class Etiquette(models.Model):
    
    nom = models.CharField(max_length=200)
    
    def __str__(self):
        return self.nom

class Fichier(models.Model):
    
    fichier = models.FileField(upload_to='GED/')
    nom_fichier = models.CharField(max_length=200)
    thumbnail = models.ImageField(upload_to='GED/thumb/',default='GED/thumb/default-fichier.jpg',blank=True)
    emetteur = models.ForeignKey(Emetteur, on_delete=models.CASCADE)
    destinataire = models.ForeignKey(Destinataire, on_delete=models.CASCADE)
    etiquette = models.ManyToManyField(Etiquette,blank=True)
    date_creation = models.DateTimeField(auto_now_add = True)
    date_modification = models.DateTimeField(auto_now = True)
    date_document = models.DateField()
    propriete_de = models.ForeignKey(User, on_delete=models.CASCADE, related_name='proprietaire_GED')
    partage_avec = models.ManyToManyField(User, blank=True, related_name='utilisateur_GED')

    def __str__(self):
        return self.nom_fichier
    
    def get_absolute_url(self):
        return reverse('fichier-detail', kwargs={'pk': self.pk})
    
# TODO ==> creer une methode post_save

ged/forms.py
from django.forms import ModelForm, FileInput, FileField
from django import forms

from .models import Fichier, Etiquette, Emetteur

class FichierUpdateForm(ModelForm):
    
    fichier = forms.FileField(
                    required=False,
                    widget = FileInput()
                )
    
    class Meta:
        
        model = Fichier
        fields = ['fichier','nom_fichier','emetteur','destinataire','date_document','etiquette']

        

ged/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.http import HttpResponseBadRequest, JsonResponse
from django.core.urlresolvers import reverse_lazy

import json

from .models import Fichier, Etiquette
from .forms import FichierUpdateForm

# Mixin pour la gestion des formulaires envoyés par AJAX --> issu du site Django https://docs.djangoproject.com/fr/1.9/topics/class-based-views/generic-editing/

class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'pk': self.object.pk,
                'nom_fichier': self.object.nom_fichier,
            }
            return JsonResponse(data)
        else:
            return response

class FichierList(ListView):
    
    model = Fichier
    context_object_name = 'fichiers'
    paginate_by = 12

    def get_context_data(self, **kwargs):
        
        context = super(FichierList, self).get_context_data(**kwargs)

        context['all_etiquette'] = Etiquette.objects.all()
        
        return context
    
    def get_template_names(self, **kwargs):
    
        if self.request.method == 'GET' and self.request.is_ajax():
        
            if self.request.GET.get("action") == "details":
        
                template_name = 'ged/fichier_list/details.html'
        
            elif self.request.GET.get("action") == "mosaique":
        
                template_name = 'ged/fichier_list/mosaique.html'
            
            elif self.request.GET.get("action") == "liste":
        
                template_name = 'ged/fichier_list/liste.html'
                
            self.request.session['vuefichier'] = template_name
            
        else:
            template_name = 'ged/fichier_list.html'
            
            if not 'vuefichier' in self.request.session:
                self.request.session['vuefichier'] = 'ged/fichier_list/mosaique.html'
            
        return template_name
    
    def get_queryset(self):
        
        queryset = Fichier.objects.all().filter(propriete_de=self.request.user)
        
        return queryset

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FichierList, self).dispatch(*args, **kwargs)
    
class FichierDetail(DetailView):

    model = Fichier
    
    def get_context_data(self, **kwargs):
        
        context = super(FichierDetail, self).get_context_data(**kwargs)

        context['all_etiquette'] = Etiquette.objects.all()
        
        return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FichierDetail, self).dispatch(*args, **kwargs)

class FichierCreate(AjaxableResponseMixin, CreateView):
    
    model = Fichier
    fields = ['fichier','nom_fichier','emetteur','destinataire','date_document','etiquette','propriete_de']
    template_name = 'ged/fichier_create_form.html'
    
    def get_initial(self):
        
        initial = super(FichierCreate, self).get_initial()
        
        initial['propriete_de'] = self.request.user
        
        return initial
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FichierCreate, self).dispatch(*args, **kwargs)

class FichierUpdate(AjaxableResponseMixin, UpdateView):
    
    model = Fichier
    form_class = FichierUpdateForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FichierUpdate, self).dispatch(*args, **kwargs)
    
class FichierDelete(AjaxableResponseMixin, DeleteView):
    model = Fichier
    success_url = reverse_lazy('fichier-list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(FichierDelete, self).dispatch(*args, **kwargs)

ged/templates/ged/fichier_confirm_delete.html
<div class='row' >
	<form action="{% url 'fichier-delete' fichier.id %}" method="post">
		{% csrf_token %}
		<p class="text-center">Voulez vous vraiment effacer {{ fichier.nom_fichier }} ?</p>
		<p class="text-center">
			<input type="submit" class="button" value="Valider">
		</p>
</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

ged/templates/ged/fichier_create_form.html
<div class="row">
	<form action="" method="post" id="addFichierSend" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			
			<input type="submit" class="button" value="Valider">  <button class='button' onclick="reloadPage()"> C'est terminé !</button>
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_document').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true
			});
		});
	</script>
	<script type="text/javascript">
		$( '#addFichierSend' )
			.submit( function( e ) {
				$.ajax( {
					success:  function() {
						$('#addFichierSend')[0].reset();
					},
					url: '{% url 'fichier-create' %}',
					type: 'POST',
					data: new FormData( this ),
					processData: false,
					contentType: false
				} );
				e.preventDefault();
				
			} );
	</script>
	<script type="text/javascript">
		function reloadPage() {
			location.reload();
		}
	</script>

ged/templates/ged/fichier_detail.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}{{ fichier.nom_fichier }}{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static "css/foundation-datepicker.min.css" %}">
{% endblock %}

{% block menu-off-canvas-small %}
{% endblock %}
{% block menu-off-canvas-medium %}
{% endblock %}

{% block content %}
    <div class='column row'>
        <h2 class='text-center'>{{ fichier.nom_fichier }}</h2>
    </div>
    <div class='row'>
        <div class='small-4 columns'>
            <img class='thumbnail' src="{{ fichier.thumbnail.url }}"/>
        </div>
        <div class='small-8 columns'>
            <p>
                <div class="button-group">
                    <button class="button success" onClick="updateFichier('{% url 'fichier-update' fichier.id %}')"><i class="fi-pencil"></i> Editer</button>
                    <button class="button"><i class="fi-share"></i> Partager</button>
                    <button class="alert button" onClick="deleteFichier('{% url 'fichier-delete' fichier.id %}')"><i class="fi-x"></i> Supprimer</button>
                </div>
            </p>
            <p> Date du document : {{ fichier.date_document }} </p>
            <p> Emetteur du document : {{ fichier.emetteur }} </p>
			<p> Destinataire du document : {{ fichier.destinataire }} </p>
            <p> Etiquettes du document : {% for etiquette in all_etiquette %}{{ etiquette.nom }}{% if not forloop.last %} | {% endif %}{% endfor %}</p>
            <p><a href='{{fichier.fichier.url}}' target="_blank" class='button'><i class="fi-download"></i> Télécharger le fichier</a></p>
        </div>
    </div>

	<div class="reveal" id="FichierUpdate" data-reveal>
	</div>
	<div class="reveal" id="FichierDelete" data-reveal>
	</div>
{% endblock %}

{% block javascript %}
	
	<script src="{% static 'js/foundation-datepicker.min.js' %}"></script>
	<script src="{% static 'js/foundation-datepicker.fr.js' %}"></script>
	
	<script type="text/javascript">
		function updateFichier($idFichier) {
			$.ajax($idFichier)
			.done(function(resp){
				$("#FichierUpdate").html(resp).foundation('open');
			});
		}
	</script>
	
	<script type="text/javascript">
		function deleteFichier($idFichier) {
			$.ajax($idFichier)
		.done(function(resp){
			$("#FichierDelete").html(resp).foundation('open');
		});
		}
	</script>
{% endblock %}

ged/templates/ged/fichier_form.html
<div class="row">
	<form action="{% url 'fichier-update' fichier.id %}" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<p class="text-center">
			<input type="submit" class="button" value="Valider">
		</p>
	</form>
</div>
<button class="close-button" data-close aria-label="Close modal" type="button">
	<span aria-hidden="true">&times;</span>
</button>

	<script type="text/javascript">
		$(function(){
			$('#id_date_document').fdatepicker({
				format: 'dd/mm/yyyy',
				disableDblClickSelection: true
			});
		});
	</script>

ged/templates/ged/fichier_list.html
{% extends "base.html" %}

{% load static from staticfiles %}

{% block title %}Liste des fichiers{% endblock %}

{% block css %}
	<link rel="stylesheet" href="{% static "css/foundation-datepicker.min.css" %}">
{% endblock %}

{% block menu-off-canvas-small %}
{% endblock %}
{% block menu-off-canvas-medium %}
{% endblock %}

{% block content %}
        <div class='row margin-bottom'>
		<div class='small-6 columns'>
			<p class="text-center"><button class='button' onClick="addFichier()">Ajouter un document <i class="fi-plus"></i></button></p>
		</div>
                <div class='small-6 columns'>
                        <div class="small button-group stacked-for-small">
                                <a class="button" onClick="changeVueFichier('details')"><i class="fi-list-thumbnails"></i> Détails</a>
                                <a class="button" onClick="changeVueFichier('liste')"><i class="fi-list"></i> Liste</a>
                                <a class="button" onClick="changeVueFichier('mosaique')"><i class="fi-thumbnails"> Mosaïque</i></a>
                        </div>
                </div>
        </div>
<span id="vue_fichier">
 {% include request.session.vuefichier %}
</span>

<div class="reveal" id="addFichierForm" data-reveal>
</div>

<!-- pagination avec filtre des catégories et recherche d'articles-->
	{% if is_paginated %}
	<div class="row">
		<ul class="pagination text-center" role="navigation" aria-label="Pagination">
			{% if page_obj.has_previous %}
				<li class="pagination-previous"><a href="{% url 'fichier-list' %}?page={{ page_obj.previous_page_number }}" aria-label="Previous page"><i class="fi-previous"></i></a></li>
				<li><a href="{% url 'fichier-list' %}?page={{ page_obj.paginator.page_range|first }}" aria-label="Page {{ page_obj.paginator.page_range|first }}">{{ page_obj.paginator.page_range|first }}</a></li>
			{% else %}
				<li class="pagination-previous disabled"><i class="fi-previous"></i></li>
			{% endif %}
				{% for page in page_obj.paginator.page_range %}
					{% if page == page_obj.number %}
						<li class="current">{{ page_obj.number }}</li>
					{% elif page == page_obj.paginator.page_range|first %}
					{% elif page == page_obj.paginator.page_range|last %}
					{% elif page == page_obj.number|add:"4" or page == page_obj.number|add:"-4" %}
						<li class="ellipsis"></li>
					{% elif page > page_obj.number|add:"4" or page < page_obj.number|add:"-4" %}
					{% else %}
						<li><a href="{% url 'fichier-list' %}?page={{ page }}" aria-label="Page {{ page }}">{{ page }}</a></li>
					{% endif %}
				{% endfor %}
			{% if page_obj.has_next %}
				<li><a href="{% url 'fichier-list' %}?page={{ page_obj.paginator.page_range|last }}" aria-label="Page {{ page_obj.paginator.page_range|last }}">{{ page_obj.paginator.page_range|last }}</a></li>
				<li class="pagination-next"><a href="{% url 'fichier-list' %}?page={{ page_obj.next_page_number }}" aria-label="Next page"><i class="fi-next"></i></a></li>
			{% else %}
				<li class="pagination-next disabled"><i class="fi-next"></i></li>
			{% endif %}
		</ul>
	</div>		
	{% endif %}
<!-- fin de la pagination -->
{% endblock %}

{% block javascript %}

	<script src="{% static 'js/foundation-datepicker.min.js' %}"></script>
	<script src="{% static 'js/foundation-datepicker.fr.js' %}"></script>

        <script type="text/javascript">
		function changeVueFichier(action){
			$.ajax({
				url:'{% url 'fichier-list' %}?page={{ page_obj.number }}',
				data: {action: action},
				dataType: "html",
				type: 'GET',
				success: function(data){
					$("#vue_fichier").empty().hide();
					$("#vue_fichier").append(data);
					$('#vue_fichier').fadeIn(2000);
					}
				});
		}
	</script>
	<script type="text/javascript">
		function addFichier() {
			$.ajax('{% url 'fichier-create' %}')
			.done(function(resp){
				$("#addFichierForm").html(resp).foundation('open');
			});
		}
	</script>

{% endblock %}